# Generated by Django 5.2 on 2025-05-09 23:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='quincena',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='quincena',
        ),
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fuente',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.categoria'),
        ),
    ]
